---
language: python
python:
  - "2.7"
  - "3.7"
  - "3.8"
env:
  - ANSIBLE_VERSION=2.8
  - ANSIBLE_VERSION=2.9

# Use the new container infrastructure
sudo: required
dist: bionic

# Install ansible
addons:
  apt:
    packages:
    - python-pip

install:
  - pip install ansible
  - pip install yamllint

  # Check ansible version
  - ansible --version

  # Create ansible.cfg with correct roles_path
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  # Basic role syntax check
  - "find . -name '*.yml' -print0 | xargs -0 yamllint -c galaxy-yamllint.yaml"
  - cd tests; ansible-playbook test.yml -i inventory --syntax-check
  - cd tests; ./run_tests.sh
  - sudo cat /etc/demo-haproxy/demo-haproxy.cfg

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
